AC-8169 :: Create Minimal Expert Navigation Tree and Landing Page
masschallenge/django-accelerator pull request #348
Opened 2020-09-29 20:13 UTC by freshprincekla

**Changes introduced in [AC-8169](https://masschallenge.atlassian.net/browse/AC-8169)**
- Add user_type to the nav tree items to enable expert only side and sub-nav items
- Add a redirect to expert overview landing page. `/dashboard/expert/overview/`

**How to test**
Checkout this PR and the sibling [PR](https://github.com/masschallenge/accelerate/pull/2768)
**Test the redirect**
- Create a new fluent page [`Expert`](http://localhost:8181/admin/fluent_pages/page/add/) and publish it as a `category header` as shown below:
<img width="1337" alt="Screen Shot 2020-09-29 at 3 27 15 PM" src="https://user-images.githubusercontent.com/16463335/94606486-8b308800-0268-11eb-820d-6e79fe136722.png">
Create another fluent page [`overview`](http://localhost:8181/admin/fluent_pages/page/add/) and publish it as a `page` as shown below:
<img width="1333" alt="Screen Shot 2020-09-29 at 3 33 36 PM" src="https://user-images.githubusercontent.com/16463335/94606972-45c08a80-0269-11eb-8482-5130cedc4266.png">
- Masquerade as an expert and see that you are redirected to `/dashboard/expert/overview/`
**Test that side nav items can be displayed according to user_type**
To ensure that the side nav items can be displayed according to user_type
- As demoadmin, go to this side nav item http://localhost:8181/admin/mc/navtree/1/change/item_82/ and set the user_type to Entrepreneur
- Masquerade as this  [expert](http://localhost:8181/admin/simpleuser/user/56778/masquerade/) user 
- See that on the side nav the item isn't displayed.

**Note:** 
Bullet-train hasn't yet been added.

2020-10-06 14:45 UTC, jonkiparsky requested changes

2020-10-06 14:45 UTC, jonkiparsky commented on accelerator_abstract/models/base_core_profile.py
> +        bt = BulletTrain(environment_id="aX45EUqSsAqhTvv5nW7WEL")
I don't love this magic number. I would prefer that it were a constant with a name telling me what it means.
Or better still, I'd like to have a function which consults bullet train and asks whether some `feature_name` is enabled. That way when we delete this code as part of the cleanup ticket, the next person to use feature flagging doesn't have to reinvent this wheel.

2020-10-06 14:45 UTC, jonkiparsky commented on accelerator_abstract/models/base_nav_tree_item.py
> +USER_TYPES = ((EXPERT_USER_TYPE, 'Expert'),
EXPERT_USER_TYPE and ENTREPRENEUR_USER_TYPE are already defined in base_base_profile.py and can be imported. USER_TYPES is also defined there, but since it includes the MEMBER_USER_TYPE which we don't want to expose here, we should probably redefine it here. In order to prevent future confusion, the name should be distinct.

2020-10-14 18:18 UTC, shakirandagire approved these changes
QA looks good to me. 
Details for what was done is on https://github.com/masschallenge/accelerate/pull/2768

2020-10-15 18:36 UTC, jonkiparsky commented on accelerator/utils.py
> +def bullet_train_access_util(feature_name):
I don't love this name. "Access" to me suggests something like a permission check, and "util" suggests an object, not a function (I know we've already made the latter mistake once in the codebase, but let's not make it a habit!)

Something like `bullet_train_feature_check` would be preferable for me.

2020-10-21 13:19 UTC, jonkiparsky approved these changes

2020-10-21 13:45 UTC, merged