[AC-8363] Add birth_year field to core profile
masschallenge/django-accelerator pull request #360
Opened 2020-11-30 13:01 UTC by iankigen

## [AC-8363](https://masschallenge.atlassian.net/browse/AC-8363)

**Changes introduced**
- add birth_year field to core profile

**Testing**
- checkout to this branch
- After [AC-7802](https://github.com/masschallenge/accelerate/pull/2800), running `make migrate` shows migrations have run successfully, however, it does not update the db tables(the cause is not yet known @philophilo will be creating a ticket for this -  [slack from Philip](https://masschallengedev.slack.com/archives/C0KPUS2CU/p1606510965364200) ). As an alternative, you can apply migrations using the impact API container. Running migration using accelerate container does not work.
   - on `impact-api/docker-compose.yml`. comment out `assets`, `front-end`, `start_dependencies` definition. Also remove `assets` and `front-end` from `web:... depends_on:` (optional - I've mentioned this just in case you need to save some build time)
   - To apply migrations: `docker-compose run --rm web ./manage.py migrate accelerator`
- Confirm that:
  - `birth_year` exists on `EntrepreneurProfile`, `ExpertProfile` and `MemberProfile` models
  - core_profile_factory to includes `birth_year` (default to null)
  - `birth_year` is a DateField
  - `birth_year` not required

2020-11-30 14:53 UTC, iankigen commented
Do not merge before the migration issue is fixed

2020-12-01 15:26 UTC, geofrocker requested changes

2020-12-01 15:26 UTC, geofrocker commented on accelerator/migrations/0027_add_birth_year_to_core_profile.py
> +            model_name='entrepreneurprofile',
this should be on the core_profile model

2020-12-01 15:30 UTC, iankigen commented on accelerator/migrations/0027_add_birth_year_to_core_profile.py
> +            model_name='entrepreneurprofile',
it is specified on the `base_core_profile` model, however, since `base_core_profile` is abstract and has no table on the db, the migrations are created for the child classes which in this case is `entrepreneurprofile`, `expertprofile` and `memberprofile`.

2020-12-01 22:32 UTC, freshprincekla approved these changes
Code changes look good,

2020-12-01 22:32 UTC, freshprincekla commented
> Do not merge before the migration issue is fixed

is this still valid or was the issue fixed?

2020-12-02 09:43 UTC, geofrocker approved these changes
QA looks good
- I am able to see the applied migration

2020-12-03 17:16 UTC, merged