[AC-8424] Investigate why migration command fails to apply migrations through accelerate instance on the local environment [Proof of concept PR]
masschallenge/django-accelerator pull request #370
Opened 2021-01-11 12:19 UTC by iankigen

## [AC-8424](https://masschallenge.atlassian.net/browse/AC-8424)

**Changes introduced**
- Add migration to alter model options: Update swappable option to None. 
It's worth mentioning that the options dict is an exact duplicate of what we have on 0001_initial.py with the swappable option set to None.

**Testing**
[local env]
- checkout to this branch
- run migrations through accelerate. 
- Confirm that migration(0028_mentorprogramofficehour_test_field.py) is applied successfully 

[test5]
- ssh and confirm that migrations are applied successfully on test5

2021-01-11 14:08 UTC, pbx commented
I've added the "Don't merge" label to this PR because altering migrations that have already run is not something we want to ship to production without careful consideration.

2021-01-12 20:32 UTC, philophilo approved these changes
Looks good
✅  migrations are applied both locally and test3

2021-01-12 21:02 UTC, shanbady requested changes
When running the migrations from a system built from scratch im getting this error:

```
  File "bin/django", line 217, in <module>
    sys.exit(djangorecipe.binscripts.manage('mcproject.develop_settings'))
  File "/srv/www/mc/current/eggs/djangorecipe-2.1.2-py3.6.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/django-accelerator/accelerator/migrations/0008_migrate_old_location_data_to_new_location_field.py", line 47, in migrate_office_hours_locations
    location_values = set(MentorProgramOfficeHour.objects.values_list(
  File "/srv/www/mc/current/eggs/Django-2.2.16-py3.6.egg/django/db/models/manager.py", line 188, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'accelerator.MentorProgramOfficeHour' has been swapped for 'mc.MentorProgramOfficeHour'
```

2021-01-12 21:10 UTC, iankigen commented
@shanbady the error you are getting is a known issue that is not directly related to this work. 
Jira ticket: https://masschallenge.atlassian.net/browse/AC-7857

2021-01-12 21:15 UTC, shanbady approved these changes
I see ok; ended up with that conclusion myself - in that event I think i can approve this

2021-01-14 16:01 UTC, merged