[AC-8490] Migrate `gender` data to `gender_identity`
masschallenge/django-accelerator pull request #381
Opened 2021-01-22 14:17 UTC by iankigen

## [AC-8490](https://masschallenge.atlassian.net/browse/AC-8490)

**Changes introduced**
- Add data migrations to migrate `gender` data to `gender_identity`

**Testing**
- Checkout to this branch and `$ make migrate`
- Confirm that all existing gender data is migrated to the gender_identity object according to the acceptance criteria on [AC-8490](https://masschallenge.atlassian.net/browse/AC-8490)

2021-01-22 14:58 UTC, jonkiparsky requested changes
One comment about performance (which may have gotten lost, thanks github) 

Higher-level comment about the desirability of this migration:
When we originally discussed the rollout of this, we decided that we would not be migrating the original data, since we would rather have users revisit this and update their identity. 
Why have we changed this decision?
@hfreund  please clarify

2021-01-22 14:58 UTC, jonkiparsky commented on accelerator/migrations/0033_migrate_gender_data.py
> +import sys
why is this imported?

2021-01-22 15:00 UTC, iankigen commented on accelerator/migrations/0033_migrate_gender_data.py
> +import sys
removed. I was using `sys.stdout` to display progress % on my dev environment

2021-01-22 15:01 UTC, jonkiparsky commented on accelerator/migrations/0033_migrate_gender_data.py
> +    for user in users:
Why are we looping over users and then calling get_profile? Why not just loop over all of the profiles?
For that matter, if it's possible to do a bulk update of gender_identity, why not filter profiles by their original gender and bulk-update them?

2021-01-22 15:54 UTC, hfreund commented
> When we originally discussed the rollout of this, we decided that we would not be migrating the original data, since we would rather have users revisit this and update their identity.
> Why have we changed this decision?

@jonkiparsky several factors caused a change in direction:
- There is a strong desire by the business to move to the new `gender_identity` field as quickly as possible; both the business and data team prefer minimizing the amount of time that two types of similar data sets exist.
- Overall delay of demographic data epic put us 4+ weeks behind the original target. A lot of new accounts were created in that time using the old gender field and the business would like them to be on the new field.
- The original plan to prompt users to take some action to review their profile and update their demographic information is partially scoped but not yet planned. The delays in shipping the demographic work cut into our window to build the follow-on deferrable modal. As other business priorities crop up there may not be enough bandwidth to deliver the deferrable modal soon enough that a majority of active users update their data to the point where we can switch all processes (i.e. judging & reporting) to using `gender_identity` instead of `gender`.

2021-01-22 20:22 UTC, jonkiparsky approved these changes
Confirmed that migration works as expected.

2021-01-27 16:41 UTC, PrinceDavis approved these changes
Migration ran successfully ✅

2021-01-27 16:41 UTC, merged