[AC-8417] Add DeferrableModal model
masschallenge/django-accelerator pull request #390
Opened 2021-02-26 12:37 UTC by iankigen

## [AC-8417](https://masschallenge.atlassian.net/browse/AC-8417)

**Changes introduced**
- Add DeferrableModal model

**Testing**
- checkout to this branch, confirm this PR meets the def of done according to [AC-8417](https://masschallenge.atlassian.net/browse/AC-8417)

[Sibling accelerate PR](url)

2021-03-01 19:00 UTC, jonkiparsky requested changes
One thing that's not clear to me: my understanding was that the "accept" button in general would be a link to some action that the user needs to take (ie, to their profile for demographics, or to a survey of some sort in another case)

I don't see where this action url is registered on this model.

2021-03-01 20:22 UTC, hfreund commented on accelerator_abstract/models/base_deferrable_modal.py
> +        help_text='Deferrable modal content. Use HTML for links.')
I would change the help text to `Modal popup content can accept HTML`. We want it to be clear that HTML is ok to use, but setting the example of a link will undermine the purpose of having a link tied to the accept/submit button.

2021-03-01 20:23 UTC, hfreund commented on accelerator_abstract/models/base_deferrable_modal.py
> +DURATION_HELP_TEXT = ('Default deferment duration. Format: '
Hours seem fine to me.

2021-03-02 16:42 UTC, iankigen commented on accelerator/migrations/0034_add_deferrable_modal_model.py
> +            name='genderchoices',
I think some changes were made to the gender choice field without a corresponding migration file since this was autogenerated by the migrate command.

2021-03-02 16:46 UTC, iankigen commented on accelerator_abstract/models/base_deferrable_modal.py
> +DURATION_HELP_TEXT = ('Default deferment duration. Format: '
Using the `DurationField` forces us to use the `days hours:minutes:seconds` format. Are you suggesting we use `IntegerField`?

2021-03-02 16:47 UTC, iankigen commented on accelerator/migrations/0034_add_deferrable_modal_model.py
> +            name='genderchoices',
I think some changes were made to the gender choice and core profile model without a corresponding migration since this was autogenerated by the migrate command.

2021-03-02 17:39 UTC, jonkiparsky commented on accelerator_abstract/models/base_deferrable_modal.py
> +DURATION_HELP_TEXT = ('Default deferment duration. Format: '
I'm okay with using the default duration field widget. It'll be a bit annoying for staff, I suppose, but it's not a huge issue for me.

2021-03-02 21:21 UTC, jonkiparsky commented on accelerator_abstract/models/base_deferrable_modal.py
> +    user_role = models.ManyToManyField(
Just wondering about this... the ManyToMany fields imply multiple values, does it make sense for these to be named in the plural, rather than in the singular?

2021-03-03 10:55 UTC, iankigen commented on accelerator_abstract/models/base_deferrable_modal.py
> +    user_role = models.ManyToManyField(
it makes sense.

2021-03-03 14:49 UTC, jonkiparsky commented on accelerator/tests/factories/deferrable_modal_factory.py
> +    def program(self, create, extracted, **kwargs):
@iankigen the `post_generation` functions for the many-to-many fields need to be renamed in accordance with the name change.

2021-03-03 14:57 UTC, jonkiparsky approved these changes

2021-03-03 15:04 UTC, merged