[AC-8173] Remove expert_nav feature-flagging
masschallenge/django-accelerator pull request #399
Opened 2021-03-23 14:52 UTC by jonkiparsky

https://masschallenge.atlassian.net/browse/AC-8173

Confirm that references to expert_nav feature flag are removed

2021-03-23 15:00 UTC, jonkiparsky commented
Coverage issue due to removing the code that hit `flag_smith_has_feature`, adding tests for this

2021-03-23 15:48 UTC, pbx requested changes
Looks good, just needs linting.
```
accelerator/tests/test_utils.py:1:1: F401 'bullet_train.BulletTrain' imported but unused
accelerator/tests/test_utils.py:13:1: W391 blank line at end of file
accelerator/tests/test_utils.py:13:1: W293 blank line contains whitespace
accelerator_abstract/models/base_core_profile.py:15:1: F401 'accelerator.utils.flag_smith_has_feature' imported but unused
```

2021-03-24 13:42 UTC, pbx approved these changes

2021-03-26 14:43 UTC, freshprincekla commented on accelerator/tests/test_utils.py
> +        with patch("bullet_train.BulletTrain.has_feature") as mock_function:
PR looks good but any reason why we are referencing bullet-train and not flagsmith?

2021-03-26 15:00 UTC, jonkiparsky commented on accelerator/tests/test_utils.py
> +        with patch("bullet_train.BulletTrain.has_feature") as mock_function:
I was surprised by this as well, but it turns out that Flagsmith has not updated the name of their client library, see [this comment](https://masschallenge.atlassian.net/browse/AC-8354?focusedCommentId=44478) and the [Flagsmith docs](https://docs.flagsmith.com/clients/python/)

2021-03-29 13:34 UTC, freshprincekla approved these changes
QA and code looks good.

2021-03-29 13:34 UTC, merged