[AC-8802] Ensure that CoreProfile has functions needed for Startup membership/ownership
masschallenge/django-accelerator pull request #407
Opened 2021-05-04 13:17 UTC by iankigen

## [AC-8802](https://masschallenge.atlassian.net/browse/AC-8802)

**Changes introduced**
- move functions needed for Startup membership/ownership to CoreProfile

**Testing**
- Confirm that the following def of done conditions are met:
  - move is_alum_in_residence and first_startup onto CoreProfile
  - make add no-op get_active_alerts to EntrepreneurProfile
  - Result of this ticket: EntrepreneurProfile defines no functions

[Sibling PR](url)

2021-05-04 13:35 UTC, iankigen commented
moving tests from accelerate to django-accelerator to fix the coverage change

2021-05-05 15:14 UTC, jonkiparsky commented on accelerator_abstract/models/base_core_profile.py
> +                program_role__program__exact=self.current_program)
This is interesting. What this specifies is that we're only interested in AIR grants for the user's `current_program`. But that field is not maintained in any way that I'm aware of, so this means this is probably incorrect. 

If we were to remove the filter on `current_program`, that would mean that an entrepreneur user is an AIR if they have an AIR grant, period. (this is already true for non-entrepreneurs) I'm not sure why this would be a bad thing. 
@hfreund Can you think of any product reason why we'd care about current_program here?

2021-05-05 15:22 UTC, jonkiparsky commented on accelerator_abstract/models/base_core_profile.py
> +        if self.user_type == ENTREPRENEUR_USER_TYPE.lower():
Sooner or later we're going to eliminate this distinction. If we stop caring about `current_program` (see below) then the only difference this makes is that for one set of users we can specify a program and get back an answer to the question "is this user an AIR in this program?".
I don't know if we're actually asking this question in the current codebase, but it seems like a reasonable thing to allow here and I don't see why we shouldn't allow it for all user types.

2021-05-05 15:23 UTC, jonkiparsky commented on accelerator/tests/test_core_profile.py
> +        user = EntrepreneurFactory(profile__current_program=air_program)
Any time a new test requires setting `current_program`, that should alarm us. Let's see if we can't get rid of this. (see comment on `base_core_profile.py`)

2021-05-05 15:25 UTC, jonkiparsky requested changes
Overall, looks good with a few minor issues.

2021-05-06 19:06 UTC, kenware commented on accelerator_abstract/models/base_core_profile.py
> +        """no op
What does this comment mean? we may remove all the comment if it does not mean anything reasonable

2021-05-06 19:08 UTC, iankigen commented on accelerator_abstract/models/base_core_profile.py
> +        """no op
it means no operation.

2021-05-06 19:15 UTC, kenware commented on accelerator_abstract/models/base_core_profile.py
> +        """no op
Since we do not need to override this function in the EntrepreneurProfile, do we still need it here?

2021-05-06 19:19 UTC, kenware approved these changes
Looks good

- [X] move is_alum_in_residence and first_startup onto CoreProfile
- [X] make add no-op get_active_alerts to EntrepreneurProfile
- [X] Result of this ticket: EntrepreneurProfile defines no functions

2021-05-06 20:28 UTC, jonkiparsky commented on accelerator_abstract/models/base_core_profile.py
> +        """no op
@kenware The purpose of this effort is to ensure that EntrepreneurProfile does not define any functionality or fields - it should inherit everything from CoreProfile.

2021-05-06 20:31 UTC, jonkiparsky approved these changes

2021-05-06 20:32 UTC, merged