[AC-8819] Move user-editable fields from ExpertProfile to CoreProfile
masschallenge/django-accelerator pull request #411
Opened 2021-05-12 13:24 UTC by iankigen

## [AC-8819](https://masschallenge.atlassian.net/browse/AC-8819)

**Changes introduced**
- move user-editable fields from ExpertProfile to CoreProfile

**Testing**
- Confirm that:
  - No user-editable fields are defined on the ExpertProfile model
  - All model forms related to entrepreneurProfile and expertProfile (such as the signup forms and team member forms) continue to function as before this ticket
 
[Sibling PR](url)

2021-05-12 13:28 UTC, iankigen commented
Fixing Lint ⌛

2021-05-13 15:36 UTC, kenware commented on accelerator_abstract/models/base_expert_profile.py
> -        max_length=255,
@iankigen how do we handle the initial movement of data from export profile to core profile

2021-05-13 16:12 UTC, kenware commented on accelerator_abstract/models/base_expert_profile.py
> -        max_length=255,
No worries, expert profiles inherit from core profiles, so the data still remain

2021-05-13 16:55 UTC, kenware commented on accelerator_abstract/models/base_expert_profile.py
>      public_website_consent_checked = models.BooleanField(
How did you categorize `public_website_consent` as user-editable but not `public_website_consent_checked`?

2021-05-13 16:56 UTC, kenware commented on accelerator_abstract/models/base_expert_profile.py
>      public_website_consent_checked = models.BooleanField(
As public_website_consent_checked was not moved

2021-05-13 17:19 UTC, iankigen commented on accelerator_abstract/models/base_expert_profile.py
>      public_website_consent_checked = models.BooleanField(
I moved all fields that can be updated by the user. `public_website_consent_checked` does not exist on any user-facing forms `/profile/`, `member/<user_id>/upgrade/`, `accounts/register/expert/`.

2021-05-13 17:29 UTC, kenware approved these changes
Looks good

2021-05-14 04:13 UTC, jonkiparsky requested changes
Code changes look reasonable, but out of an abundance of caution I want to do deep QA on this before approving.

2021-05-26 19:15 UTC, jonkiparsky approved these changes

2021-05-26 19:15 UTC, merged