[AC-9028] Create algolia index for community directory
masschallenge/django-accelerator pull request #428
Opened 2021-08-05 19:41 UTC by iankigen

## [AC-9028](https://masschallenge.atlassian.net/browse/AC-9028)

**Testing**
- Visit https://www.algolia.com/apps/3WW3PBJ1CW/explorer/browse/dev_community?searchMode=search (Final reindex in progress : test-ian vAC-9028v0.3)
- Confirm that the following conditions are satisfied:
  - Create an index for the Community directory

    - index on CoreProfile

    - index name is “Community”

    - index the same fields currently indexed for Mentor and People directories (union of the set)

    - prod, staging, and dev indexes (as we currently do for Mentor and People directories)

    - Filters will include Industry, Subindustry, Role (Finalist, Alumni, Mentor, Staff), Specialty (Investor, Executive, Lawyer), office hours availability

    - New filter: Program participation - user has Finalist or Confirmed Mentor role grant in an active program 

   - determine when this index needs to be updated and provide or recommend a mechanism for that 
       - `office_hour_programs`  field is updated (partial-reindex) when an OH session is created
       - `Coreprofile` model is automatically updated when a Create|Update|Delete action happens (functionality provided by `algoliasearch_django`)
      
[Sibling PR](url)

2021-08-10 13:14 UTC, jonkiparsky commented on accelerator/models/core_profile.py
> +        ).exists()
This line break is not needed and impedes readability

2021-08-10 13:23 UTC, freshprincekla approved these changes
Changes look good to me.

2021-08-12 14:40 UTC, jonkiparsky requested changes
A few trivial bits of cleanup. 

I'm a little concerned by the number of queries that seem to be required to index a profile, but that's not new here. Possibly worth looking into, but not a blocker.

2021-08-12 14:40 UTC, jonkiparsky commented on accelerator/models/core_profile.py
> +ACTIVE_PROGRAM = Q(program_role__program__program_status='active')
Can we use ACTIVE_PROGRAM_STATUS here?

2021-08-12 14:40 UTC, jonkiparsky commented on accelerator/tests/test_core_profile.py
> +    program_role = ProgramRoleFactory.create(
`.create` is not required for Factory calls

2021-08-12 14:40 UTC, jonkiparsky commented on accelerator/tests/test_core_profile.py
> +    ProgramRoleGrantFactory.create(
`.create` is not required for Factory calls

2021-08-12 20:42 UTC, jonkiparsky commented on accelerator/models/core_profile.py
> +ACTIVE_PROGRAM = Q(program_role__program__program_status='active')
Sorry, I was saying we should use `ACTIVE_PROGRAM_STATUS` rather than the literal `'active'`

I'm fine with `ACTIVE_PROGRAM` as the name of this `Q` object. (or `HAS_ACTIVE_PROGRAM_STATUS`, either way)

2021-08-13 13:30 UTC, jonkiparsky approved these changes

2021-08-13 13:30 UTC, merged