[AC-9123] Remove Finalist tag from all staff accounts
masschallenge/django-accelerator pull request #447
Opened 2021-11-10 13:32 UTC by AmosWels

Changes introduced in [AC-9123](https://masschallenge.atlassian.net/browse/AC-9123)

Remove Finalist tag from all staff accounts

**How to test:**

- Check out this branch
- Run Migrations on your localhost
- Notice that no staff user has a finalist role grant

2021-11-15 15:24 UTC, shakirandagire approved these changes
Code changes look good to me

2021-11-19 13:00 UTC, iankigen requested changes

2021-11-19 13:00 UTC, iankigen commented on accelerator/migrations/0075_auto_20211112_1309.py
> +                person_id__in=staff_ids).values_list(
instead of getting the id values list then deleting each program role grant in a loop, it is much more efficient to do this instead:
```
ProgramRoleGrant.objects.filter(
                program_role__user_role__name='Finalist',
                person_id__in=staff_ids).delete()

2021-11-19 13:57 UTC, AmosWels commented on accelerator/migrations/0075_auto_20211112_1309.py
> +        is_staff=True).values_list('id', flat=True)
thanks, let me update this query

2021-11-19 18:22 UTC, iankigen commented on accelerator/migrations/0075_auto_20211112_1309.py
> +            staff_ids.append(user.id)
instead of doing this with a loop which is always very expensive
we can have
```
staff_ids = set(Clearance.objects.all().values_list('user__pk', flat=True)).union(set(User.objects.filter(is_superuser=True).values_list('pk', flat=True)))

2021-11-19 18:22 UTC, iankigen commented
we have a failing build

2021-11-19 19:05 UTC, AmosWels commented on accelerator/migrations/0075_auto_20211112_1309.py
> +            staff_ids.append(user.id)
this gets rid of the `is_employee` check that was earlier suggested

2021-11-19 19:28 UTC, iankigen commented on accelerator/migrations/0075_auto_20211112_1309.py
> +            staff_ids.append(user.id)
def is_employee(user) was meant to be used as a reference on how to get a staff user

2021-11-19 20:46 UTC, AmosWels commented
> we have a failing build

>Noticed this failing build and tried resolving it with the git config though it persists. Any pointers are welcome

2021-11-19 21:22 UTC, jonkiparsky commented
> > we have a failing build
> 
> > Noticed this failing build and tried resolving it with the git config though it persists. Any pointers are welcome

Since this is running under travis, local git config changes won't fix it. 

I'm trying to understand what the issue is, not sure yet. It first appears at https://github.com/masschallenge/django-accelerator/pull/447/commits/d9fe970a1a66b60017832afbf07931dc89037c70 which seems clean.

2021-11-19 21:24 UTC, jonkiparsky commented on accelerator/migrations/0075_auto_20211112_1309.py
> +# Generated by Django 2.2.10 on 2021-11-12 18:09
@AmosWels Can you please give this migration a descriptive name?

2021-11-19 21:28 UTC, kenware commented on accelerator/migrations/0075_auto_20211112_1309.py
> +    staff_ids = set(Clearance.objects.all().values_list(
This query takes all user that has any clearance as staff. @iankigen advice if I am wrong.

2021-11-19 21:48 UTC, jonkiparsky commented on accelerator/migrations/0075_auto_20211112_1309.py
> +    staff_ids = set(Clearance.objects.all().values_list(
@kenware That is correct. Users who have Clearances are presumed to be staff.

2021-11-19 21:52 UTC, kenware commented on accelerator/migrations/0075_auto_20211112_1309.py
> +    staff_ids = set(Clearance.objects.all().values_list(
@AmosWels you need to filter users with staff clearances and do a union with superusers.

2021-11-23 16:19 UTC, closed without merging