[AC-9247]: Change program family query to use rolegrants
masschallenge/django-accelerator pull request #456
Opened 2021-11-24 11:52 UTC by kenware

[AC-9247](https://masschallenge.atlassian.net/browse/AC-9247)

 How to test:
 - Ensure program filter uses program family names from program role grant

2021-11-26 12:19 UTC, iankigen reviewed
Code looks good. 
Waiting for a reindex to finish QA

2021-11-26 14:24 UTC, iankigen commented on accelerator_abstract/models/base_core_profile.py
> +            ]
I had missed the comment on the ticket: https://masschallenge.atlassian.net/browse/AC-9247?focusedCommentId=45432

the filter should only care about program role grants for Finalists, Confirmed Mentors, and Alumni. 
Also, program_status filter should not be included (I see no requirement for this in the ticket)

2021-11-29 15:15 UTC, jonkiparsky requested changes
Changes look good, test fails when run against development, which is good. 

Two minor changes requested, but this should be good to go once those are addressed.

2021-11-29 17:32 UTC, kenware commented on accelerator_abstract/models/base_core_profile.py
> +        return self.user.programrolegrant_set.filter(
This line is more than 78 characters `program_roles = self.user.programrolegrant_set.filter(program_role__user_role__name__in=[` . so I am using this format

```
program_roles = self.user.programrolegrant_set.filter(
         program_role__user_role__name__in=[BaseUserRole.FINALIST,
                                                                        BaseUserRole.ALUM, 
                                                                        BaseUserRole.MENTOR])
        return program_roles.values_list('program_role__program__program_family__name',
                                                               flat=True)
```

2021-12-01 11:36 UTC, iankigen reviewed
From QA
- Active accounts with Finalist role grants appear in the Community directory when the Finalist filter is applied ✅ 

- Active accounts with a Program Role Grant appear in the Community directory when their program family filter is applied ✅ 

- Active accounts with an Alum role grant appear in the Community directory when the Alum filter is applied ✅

2021-12-01 11:36 UTC, iankigen commented on accelerator_abstract/models/base_core_profile.py
> +            'program_role__program__program_family__name', flat=True))
Noticed some redundant program_family names. This should be distinct()

2021-12-01 14:49 UTC, jonkiparsky commented
@kenware lint issue
```
0.51s$ make code-check
accelerator_abstract/models/base_core_profile.py:494:80: E501 line too long (81 > 79 characters)
Makefile:126: recipe for target 'code-check' failed
make: *** [code-check] Error 123
```

2021-12-01 18:36 UTC, iankigen approved these changes

2021-12-01 18:36 UTC, merged