[AC-9445] Add IndustryCluster model
masschallenge/django-accelerator pull request #501
Opened 2022-04-19 16:45 UTC by AmosWels

## [AC-9444](https://masschallenge.atlassian.net/browse/AC-9444)

**Changes introduced**
- add the IndustryCluster model

**Testing**
- Checkout branch `AC-9445` and run `make migrate` on the accelerate repo,
- Confirm that the def of done according to [AC-9445](https://masschallenge.atlassian.net/browse/AC-9445) is met

Creating Sibling PR :hourglass_flowing_sand:

2022-04-19 16:54 UTC, iankigen commented on accelerator/models/industry_cluster.py
> +from __future__ import unicode_literals
no need for unicode_literals

2022-04-19 16:54 UTC, iankigen commented on accelerator/models/industry_cluster.py
> +            "IndustryCluster")
no need to use swapper

2022-04-19 16:55 UTC, iankigen commented
we have some lint issues

2022-04-20 15:42 UTC, iankigen reviewed
Looks good

2022-04-20 15:42 UTC, iankigen commented on accelerator/tests/factories/industry_cluster_factory.py
> +        lambda n: "Program interested in Climate {0}".format(n))
Probably should be "Industry Cluster {}" instead of climate cluster

2022-04-20 17:35 UTC, iankigen approved these changes

2022-04-21 11:52 UTC, shakirandagire approved these changes
QA looks good to me
 ✅ Model is created as per the definition of done and its migration exists
 ✅ IndustryCluster model is added to the admin site
<img width="582" alt="Screenshot 2022-04-21 at 14 45 30" src="https://user-images.githubusercontent.com/6957960/164451933-12913c47-9751-4e64-93bb-6405ad7a3261.png">
✅ Add IndustryClusterFactory with sensible default values
✅ add M2M relationship to:
CoreProfile - industry_cluster_interest
Program - supported_industry_clusters
✅ supported_industry_clusters option is added to the [Program administration site](http://staging.masschallenge.org/admin/mc/program/
<img width="866" alt="Screenshot 2022-04-21 at 14 51 32" src="https://user-images.githubusercontent.com/6957960/164452346-81790702-e1d9-444c-959c-4a92ea733181.png">
)

2022-04-21 16:03 UTC, iankigen commented on accelerator/tests/factories/core_profile_factory.py
> +    def program_location_interest(self, create, extracted, **kwargs):
needs `@post_generation` decorator

2022-04-22 11:04 UTC, iankigen commented on accelerator_abstract/models/base_industry_cluster.py
> +        abstract = True
this does not match what exists on the migration file

2022-04-22 11:05 UTC, iankigen requested changes
Inconsistent model and migration

2022-04-22 12:21 UTC, iankigen approved these changes

2022-04-22 12:27 UTC, merged