[AC-9452] 1 Add program interest fields to Program model
masschallenge/django-accelerator pull request #503
Opened 2022-04-20 15:45 UTC by shakirandagire

**Changes made to [AC-9452](https://masschallenge.atlassian.net/browse/AC-9452):**
- Added fields in Program Model.

**How to test:**

- On this branch on accelerate, run `make migrate`
- Login or masquerade as a user with admin privileges.
- Checkout http://localhost:8181/admin.
- Ensure that you are able to see the fields in Program as indicated in the done of [AC-9452](https://masschallenge.atlassian.net/browse/AC-9452)

[Sibling PR](https://github.com/masschallenge/accelerate/pull/3252)

2022-04-20 15:50 UTC, iankigen commented on accelerator/migrations/0099_update_program_model.py
> +    ]
EOF newline

2022-04-20 15:50 UTC, iankigen reviewed
We have lint, otherwise, looks good

2022-04-20 16:28 UTC, AmosWels commented on accelerator/migrations/0099_update_program_model.py
> +            field=models.ImageField(null=True, upload_to=''),
suggestion: could specify a directory path for the upload

2022-04-21 16:27 UTC, iankigen reviewed
we have conflicting migrations

2022-04-21 16:57 UTC, iankigen approved these changes

2022-04-22 11:08 UTC, iankigen requested changes

2022-04-22 11:08 UTC, iankigen commented on accelerator/migrations/0101_update_program_model.py
> +              upload_to='program_images'),
syntax error

2022-04-22 11:53 UTC, iankigen commented on accelerator_abstract/models/base_program.py
> +        null=True
This should be `null=True, blank=False`

2022-04-22 15:16 UTC, iankigen approved these changes

2022-04-22 15:24 UTC, AmosWels approved these changes
changes look good. successfully run migrations

2022-04-22 15:24 UTC, merged